#' @title Extract phenological metrics
#' @description Extract phenological metrics from a fitted time series.
#' @param ts Time series in `s2ts` format (generated using `extract_s2ts()` or `smooth_s2ts()`).
#' @param cycles Cycles allocation (data table generated by [`cut_cycles()`],
#'  eventually filtered using [`assign_season()`]).
#' @param value_type (optional) Character: 
#'  - if `"absolute"`, value set with argument `min_diff` is an absolute value;
#'  - if `"senescence"`, value set with argument `min_diff` is a 
#'      a relative measure among the maximum (peak) and the minimum (after drop);
#'  - if `"cycle"` (default), value set with argument `min_diff` is a 
#'      a relative measure among the range of the specific cycle;
#'  - if `"season"`, value set with argument `min_diff` is a 
#'      a relative measure among the range of the crop season;
#' @param min_qa (optional) minimum 0-1 quality value
#'  (points with `qa < min_qa` are not used, while `qa` values
#'  in the range `min_qa` to 1 are reshaped into the range 0 to 1).
#'  Default is 0.5. It only applies if `ts` is a raw TS.
#' @return A data table with the following fields:
#'  - `id`: the time series ID (see `s2ts`);
#'  - `year`: the year (integer);
#'  - `cycle`: the cycle ID (integer);
#'  - `begin`, `end`, `maxval`: the dates of begin, end and maximum value in
#'      the cycle as computed by `cut_cycles()`;
#'  - other phenology metrics, depending on `method`:
#'      - if `method = "trs"` or `"derivatives"`: `sos`, `eos`, `los`, `pop`,
#'          `mgs`, `rsp`, `rau`, `peak`, `msp`, `mau` (see
#'          `phenopix::PhenoTrs()` or `phenopix::PhenoDeriv()`);
#'      - if `method = "gu"`: `UD`, `SD`, `DD`, `RD`, `maxline`, `baseline`,
#'          `prr`, `psr`, `plateau.slope` (see `phenopix::PhenoGu()`);
#'      - if `method = "klosterman"`: `Greenup`, `Maturity`, `Senescence`,
#'          `Dormancy` (see `phenopix::PhenoKl()`).
#' @author Luigi Ranghetti, PhD (2020) \email{luigi@@ranghetti.info}
#' @import data.table
#' @export
#' @examples
#' # Load input data
#' data("cf")
#' data("ts_filled") # used for plots
#' 
#' # Default extraction ("trs" method with 50% threshold)
#' dt_pheno <- extract_pheno(cf)
#' plot(ts_filled, fitted = cf, pheno = dt_pheno, plot_dates = TRUE)
#' 
#' \donttest{
#' # Customize parameters (e.g. "derivatives" method with 30% threshold)
#' dt_pheno_2 <- extract_pheno(cf, method = "derivatives", trs = 0.3)
#' plot(ts_filled, fitted = cf, pheno = dt_pheno_2, plot_dates = TRUE)
#' 
#' # Other methods: Klosterman
#' dt_pheno_kl <- extract_pheno(cf, method = "klosterman")
#' plot(ts_filled, fitted = cf, pheno = dt_pheno_kl, plot_dates = TRUE)
#' 
#' # Other methods: Gu
#' dt_pheno_gu <- extract_pheno(cf, method = "gu")
#' plot(ts_filled, fitted = cf, pheno = dt_pheno_gu, plot_dates = TRUE)
#' }


extract_mowing <- function(
    ts, cycles,
    # min_sen = 0.7, # soglia massima (assoluta o relativa; se relativa, tra il picco -1- e il valore minimo dopo il picco -0-) per considerare il prato come non ancora tagliato poiché senescente
    # max_bs = 0.1, # soglia massima (come sopra) per considerare il prato come completamente tagliato
    min_diff = 0.5, # minima differenza (assoluta o relativa) nella finestra mow come definita in base ai due parametri successivi
    max_n_mow = 3, # massimo numero di immagini tra il taglio non iniziato e il taglio finito
    max_d_mow = 10, # numero massimo di giorni tra un'immagine a taglio in corso e una a taglio non iniziato o finito
    value_type = "cycle",
    min_qa = 0.6
) {
  
  # Avoid check notes for data.table related variables

  ## Check arguments
  # TODO
  if (!value_type %in% c("cycle", "season", "senescence", "absolute")) {
    stop('"value_type" not recognized.')
  }
  
  # Fit for each ID/cycle
  ts_dt <- if (attr(ts, "gen_by") == "smooth_s2ts") {
    as.data.table(ts)[!is.na(value),]
  } else if (attr(ts, "gen_by") == "extract_s2ts") {
    as.data.table(ts)[qa >= min_qa,]
  } else stop("`ts` must be a raw or smoothed time series (not filled).")
  mow_out <- list()
  for (sel_id in unique(ts_dt$id)) {
    mow_out[[sel_id]] <- list()
    for (sel_year in cycles[id == sel_id, unique(year)]) {
      mow_out[[sel_id]][[as.character(sel_year)]] <- list()
      if (value_type == "season") {
        sel_seas_date <- range(as.Date(as.matrix(cycles[id == sel_id & year == sel_year,][,list(begin, end)])))
        abs_range <- ts_dt[id == sel_id & date >= sel_seas_date[1] & date <= sel_seas_date[2]+1, range(value, na.rm=TRUE)]
      }
      for (sel_cycle in cycles[id == sel_id & year == sel_year, unique(cycle)]) {
        sel_cut_date <- as.Date(as.matrix(cycles[id == sel_id & year == sel_year & cycle == sel_cycle,][,list(begin, maxval, end)])[1,])
        sel_ts_sen <- ts_dt[id == sel_id & date >= sel_cut_date[2] & date <= sel_cut_date[3]+1, ]
        if (value_type == "senescence") {
          abs_range <- sel_ts_sen[,range(value, na.rm=TRUE)]
        } else if (value_type == "cycle") {
          abs_range <- ts_dt[id == sel_id & date >= sel_cut_date[1] & date <= sel_cut_date[3]+1, range(value, na.rm=TRUE)]
        }
        if (value_type == "absolute") {
          sel_ts_sen[,relval := value]
        } else {
          sel_ts_sen[,relval := (value - min(value, na.rm=TRUE)) / diff(abs_range)]
        }
        # calcola le date candidate di inizio-fine sfalcio
        for (sel_date in sel_ts_sen$date) {
          sel_maxval <- sel_ts_sen[date==sel_date,relval]
          sel_firstmowdate <- sel_ts_sen[date>sel_date & relval<sel_maxval-min_diff,][1, date]
          sel_mowing <- sel_ts_sen[date>sel_date & date<sel_firstmowdate,]
          sel_mowing_n <- sel_mowing[, .N]
          # sel_mowing_d <- sel_mowing[, as.integer(diff(range(date)))]
          sel_ts_sen[
            date==sel_date, 
            start_mow := !is.na(sel_firstmowdate) & 
              sel_mowing_n <= max_n_mow & 
              (max(as.integer(sel_mowing$date - sel_date)) <= max_d_mow |
                 max(as.integer(sel_firstmowdate - sel_mowing$date)) <= max_d_mow)
          ]
          sel_ts_sen[date==sel_date & start_mow==TRUE, end_mow := sel_firstmowdate]
          sel_ts_sen[date==sel_date & start_mow==TRUE, relval_min := sel_ts_sen[date==sel_firstmowdate, relval]]
          sel_ts_sen[date==sel_date & start_mow==TRUE, mow_w := relval - relval_min]
        }
        # interpolale
        # sel_ts_record <- sel_ts_sen[mow_w==max(mow_w,na.rm=TRUE),] # criterio della masisma differenza
        sel_ts_record <- sel_ts_sen[relval_min==min(relval_min,na.rm=TRUE),] # criterio del minimo minimo
        sel_ts_mow <- sel_ts_sen[
          date >= sel_ts_record[, date] &
            date <= sel_ts_record[, end_mow],
          list(date, relval)
        ]
        if (nrow(sel_ts_mow)>1) {
        sel_ts_mow_spline <- as.data.table(approx(
          x = sel_ts_mow$date,
          y = sel_ts_mow$relval,
          xout = seq(min(sel_ts_mow$date),max(sel_ts_mow$date),by=1)
        ))
        cycles[
          id == sel_id & year == sel_year & cycle == sel_cycle, 
          c("mowing","mowing_start","mowing_end") := list(
            sel_ts_mow_spline[y <= mean(sel_ts_mow[c(1,.N),relval]),][1,x],
            sel_ts_mow_spline[1,x], sel_ts_mow_spline[.N,x]
          )
        ]
        }
      } # end of sel_cycle FOR cycle
    } # end of sel_year FOR cycle
  } # end of id FOR cycle
  
  attr(cycles, "gen_by") <- "extract_mowing"
  cycles
  
}
