#' @title Extract mowing dates
#' @description Extract mowing dates from a raw or smoothed time series.
#' @param ts Time series in `s2ts` format (generated using `extract_s2ts()`
#'  or `smooth_s2ts()` -- **not** `fill_s2ts()`).
#' @param cycles Cycles allocation (data table generated by [`cut_cycles()`],
#'  eventually filtered using [`assign_season()`]).
#' @param min_diff minimum difference (absolute or relative, depending on
#'  argument `value_type`) among pre- and post-event values to discriminate 
#'  a mowing window (default: 0.5).
#' @param max_post maximum post-event value (absolute or relative, depending on
#'  argument `value_type`) to discriminate a mowing window (default: 0.3).
#' @param max_length maximum number of days passing among pre- and post-event
#'  dates to discriminate a mowing window (default: no limit).
#' @param max_n_mow maximum allowed number of images among pre- and post-event
#'  dates (default: 3).
#' @param max_d_mow maximum number of days between an intermediate image and
#'  a pre- or post-event date (default: 10).
#' @param value_type (optional) Character: 
#'  - if `"absolute"`, value set with argument `min_diff` is an absolute value;
#'  - if `"senescence"` (default) value set with argument `min_diff` is a 
#'      a relative measure among the maximum (peak) and the minimum (after drop);
#'  - if `"cycle"` value set with argument `min_diff` is a 
#'      a relative measure among the range of the specific cycle;
#'  - if `"season"` value set with argument `min_diff` is a 
#'      a relative measure among the range of the crop season;
#' @param min_qa (optional) minimum 0-1 quality value
#'  (points with `qa < min_qa` are not used, while `qa` values
#'  in the range `min_qa` to 1 are reshaped into the range 0 to 1).
#'  Default is 0.5. It only applies if `ts` is a raw TS.
#' @return A data table with the following fields:
#'  - `id`: the time series ID (see `s2ts`);
#'  - `year`: the year (integer);
#'  - `cycle`: the cycle ID (integer);
#'  - `begin`, `end`, `maxval`: the dates of begin, end and maximum value in
#'      the cycle as computed by `cut_cycles()`;
#'  - other columns included in input `cycle` dt (e.g. `"weight"`);
#'  - `mowing`: estimated mowing date;
#'  - `mowing_start`: estimated date of beginning of mowing phase;
#'  - `mowing_end`: estimated date of ending of mowing phase.
#' @author Luigi Ranghetti, PhD (2024)
#' @import data.table
#' @importFrom stats approx
#' @export
#' @examples
#' # Load input data
#' data("ts_raw")
#' data("dt_cycles")
#' data("ts_filled") # used for plots
#' 
#' # Default extraction ("trs" method with 50% threshold)
#' mowing_dt <- extract_mowing(ts_raw, dt_cycles) 
#' plot(ts_filled, pheno = dt_cycles, plot_points = TRUE) +
#'   ggplot2::geom_vline(ggplot2::aes(xintercept=mowing), mowing_dt, linetype="dashed")


extract_mowing <- function(
    ts, cycles,
    min_diff = 0.5,
    max_post = 0.3,
    max_length = Inf,
    max_n_mow = 3,
    max_d_mow = 10,
    value_type = "senescence",
    min_qa = 0.6
) {
  
  # Avoid check notes for data.table related variables
  
  ## Check arguments
  # TODO
  if (!value_type %in% c("absolute", "senescence", "cycle", "season")) {
    stop("Argument 'value_type' not recignised.")
  }
  
  # Fit for each ID/cycle
  ts_dt <- if (attr(ts, "gen_by") == "smooth_s2ts") {
    as.data.table(ts)[!is.na(value),]
  } else if (attr(ts, "gen_by") == "extract_s2ts") {
    as.data.table(ts)[qa >= min_qa,]
  } else stop("`ts` must be a raw or smoothed time series (not filled).")
  mow_out <- list()
  for (sel_id in unique(ts_dt$id)) {
    mow_out[[sel_id]] <- list()
    for (sel_year in cycles[id == sel_id, unique(year)]) {
      mow_out[[sel_id]][[as.character(sel_year)]] <- list()
      if (value_type == "season") {
        sel_seas_date <- range(as.Date(as.matrix(cycles[id == sel_id & year == sel_year,][,list(begin, end)])))
        abs_range <- ts_dt[id == sel_id & date >= sel_seas_date[1] & date <= sel_seas_date[2]+1, range(value, na.rm=TRUE)]
      }
      for (sel_cycle in cycles[id == sel_id & year == sel_year, unique(cycle)]) {
        sel_cut_date <- as.Date(as.matrix(cycles[id == sel_id & year == sel_year & cycle == sel_cycle,][,list(begin, maxval, end)])[1,])
        sel_ts_sen <- ts_dt[id == sel_id & date >= sel_cut_date[2] & date <= sel_cut_date[3]+1, ]
        if (value_type == "senescence") {
          abs_range <- sel_ts_sen[,range(value, na.rm=TRUE)]
        } else if (value_type == "cycle") {
          abs_range <- ts_dt[id == sel_id & date >= sel_cut_date[1] & date <= sel_cut_date[3]+1, range(value, na.rm=TRUE)]
        }
        if (value_type == "absolute") {
          sel_ts_sen[,relval := value]
        } else {
          sel_ts_sen[,relval := (value - min(value, na.rm=TRUE)) / diff(abs_range)]
        }
        # calcola le date candidate di inizio-fine sfalcio
        for (sel_date in sel_ts_sen$date) {
          sel_maxval <- sel_ts_sen[date==sel_date,relval]
          sel_firstmowdate <- sel_ts_sen[date>sel_date & relval<sel_maxval-min_diff,][1, date]
          if (is.na(sel_firstmowdate)) {
            sel_ts_sen[date==sel_date, start_mow := FALSE]
          } else {
            sel_mowing <- sel_ts_sen[date>sel_date & date<sel_firstmowdate,]
            sel_mowing_n <- sel_mowing[, .N]
            # sel_mowing_d <- sel_mowing[, as.integer(diff(range(date)))]
            sel_ts_sen[
              date==sel_date, 
              start_mow := sel_mowing_n <= max_n_mow & 
                relval == sel_ts_sen[date>=sel_date, max(relval)] &
                sel_ts_sen[date==sel_firstmowdate,relval] <= max_post &
                (max(as.integer(sel_mowing$date - sel_date)) <= max_d_mow |
                   max(as.integer(sel_firstmowdate - sel_mowing$date)) <= max_d_mow)
            ]
          }
          sel_ts_sen[date==sel_date & start_mow==TRUE, end_mow := sel_firstmowdate]
          sel_ts_sen[date==sel_date & start_mow==TRUE, relval_min := sel_ts_sen[date==sel_firstmowdate, relval]]
          sel_ts_sen[date==sel_date & start_mow==TRUE, mow_w := relval - relval_min]
          # interpolale
          # sel_ts_record <- sel_ts_sen[mow_w==max(mow_w,na.rm=TRUE),] # criterio della massima differenza
          if (sel_ts_sen[,sum(!is.na(relval_min))] > 0) {
            sel_ts_record <- sel_ts_sen[relval_min==min(relval_min,na.rm=TRUE),] # criterio del minimo minimo
            sel_ts_mow <- sel_ts_sen[
              date >= sel_ts_record[, date] &
                date <= sel_ts_record[, end_mow],
              list(date, relval)
            ]
            # if (nrow(sel_ts_mow)>1) {
            if (as.integer(sel_ts_mow[.N,date] - sel_ts_mow[1,date]) < max_length) {
              sel_ts_mow_spline <- as.data.table(approx(
                x = sel_ts_mow$date,
                y = sel_ts_mow$relval,
                xout = seq(min(sel_ts_mow$date),max(sel_ts_mow$date),by=1)
              ))
              cycles[
                id == sel_id & year == sel_year & cycle == sel_cycle, 
                c("mowing","mowing_start","mowing_end") := list(
                  sel_ts_mow_spline[y <= mean(sel_ts_mow[c(1,.N),relval]),][1,x],
                  sel_ts_mow_spline[1,x], sel_ts_mow_spline[.N,x]
                )
              ]
            }
          }
        }
      } # end of sel_cycle FOR cycle
    } # end of sel_year FOR cycle
  } # end of id FOR cycle
  
  attr(cycles, "gen_by") <- "extract_mowing"
  cycles
  
}
